direction: right

classes: {
  Layer: {
    shape: circle
    style: {
      stroke: blue
      stroke-dash: 3
      fill: honeydew
    }
  }

  Package: {
    shape: package
  }

  DependencyLine: {
    style: {
      stroke: green
      stroke-dash: 3
    }
  }
}

title: |md
  # Package Dependency
|

l1: "" {
  class: Layer

  l2: "" {
    class: Layer

    l3: "" {
      class: Layer

      l4: "" {
        class: Layer

        profile: pkg/profile {
          class: Package
        }
      }

      postgres: pkg/postgres {
        class: Package
      }

      tls: pkg/tls {
        class: Package
      }

      httpserver: pkg/httpserver {
        class: Package
      }

      httpclient: pkg/httpclient {
        class: Package
      }

      tenantservice: pkg/tenantservice {
        class: Package
      }
    }

    cmd: pkg/cmd {
      class: Package
    }
    otel: pkg/otel {
      class: Package
    }
  }

  main: cmd {
    class: Package
  }
}
l1 -> l1.l2 -> l1.l2.l3 -> l1.l2.l3.l4: {
  class: DependencyLine
}
l1 -> misc: {
  class: DependencyLine
}

misc: {
  near: bottom-right
  class: Layer

  util: pkg/util {
    class: Package
  }
  logger: pkg/logger {
    class: Package
  }
}
