direction: right
vars: {
  d2-config: {
    pad: 0
    center: true
    sketch: true
    layout-engine: elk
  }
}

classes: {
  Layer: {
    shape: circle
    style: {
      stroke: blue
      stroke-dash: 3
      fill: honeydew
    }
    width: 777
  }

  Package: {
    shape: package
  }

  DependencyLine: {
    style: {
      stroke: green
      stroke-dash: 3
    }
  }
}

title: |md
  # Package Dependency
|

l1: "" {
  class: Layer

  l2: "" {
    class: Layer

    l3: "" {
      class: Layer

      l4: "" {
        class: Layer

        profile: internal/profile {
          class: Package
        }
      }

      httpserver: internal/httpserver {
        class: Package
      }

      postgres: internal/postgres {
        class: Package
      }

      kafka: internal/kafka {
        class: Package
      }

      tenantservice: internal/tenantservice {
        class: Package
      }
    }

    cmd: internal/cmd {
      class: Package
    }
  }

  main: cmd/profile {
    class: Package
  }
}
l1 -> l1.l2 -> l1.l2.l3 -> l1.l2.l3.l4: {
  class: DependencyLine
}

l1 -> reusable.log: {
  class: DependencyLine
}
l1.l2.cmd -> reusable.cmd: {
  class: DependencyLine
}
l1.l2.cmd -> reusable.otelinit: {
  class: DependencyLine
}
l1.l2.cmd -> reusable.util: {
  class: DependencyLine
}
l1.l2.cmd -> reusable.tlswrap: {
  class: DependencyLine
}
l1.l2.cmd -> reusable.httpclient: {
  class: DependencyLine
}
l1.l2.l3.postgres -> reusable.tinkx: {
  class: DependencyLine
}
l1.l2.l3.postgres -> reusable.outboxce: {
  class: DependencyLine
}
l1.l2.l3.kafka -> reusable.outboxce: {
  class: DependencyLine
}

reusable: Reusable Library {
  near: bottom-right
  class: Layer

  cmd: pkg/cmd {
    class: Package
  }
  tinkx: pkg/tinkx {
    class: Package
  }
  log: pkg/log {
    class: Package
  }
  otelinit: pkg/otelinit {
    class: Package
  }
  outboxce: pkg/outboxce {
    class: Package
  }
  filewatch: pkg/filewatch {
    class: Package
  }
  tlswrap: pkg/tlswrap {
    class: Package
  }
  httpclient: pkg/httpclient {
    class: Package
  }
  util: pkg/util {
    class: Package
  }

  cmd -> util: {class: DependencyLine}
  cmd -> tinkx: {class: DependencyLine}
  cmd -> log: {class: DependencyLine}
  cmd -> otelinit: {class: DependencyLine}
  cmd -> tlswrap: {class: DependencyLine}
  cmd -> httpclient: {class: DependencyLine}
  tlswrap -> filewatch: {class: DependencyLine}
  tlswrap -> log: {class: DependencyLine}
}
