// Code generated by mockery v2.43.2. DO NOT EDIT.

package profilemock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	profile "github.com/telkomindonesia/go-boilerplate/internal/profile"

	uuid "github.com/google/uuid"
)

// MockTenantRepository is an autogenerated mock type for the TenantRepository type
type MockTenantRepository struct {
	mock.Mock
}

type MockTenantRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTenantRepository) EXPECT() *MockTenantRepository_Expecter {
	return &MockTenantRepository_Expecter{mock: &_m.Mock}
}

// FetchTenant provides a mock function with given fields: ctx, id
func (_m *MockTenantRepository) FetchTenant(ctx context.Context, id uuid.UUID) (*profile.Tenant, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FetchTenant")
	}

	var r0 *profile.Tenant
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*profile.Tenant, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *profile.Tenant); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*profile.Tenant)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTenantRepository_FetchTenant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchTenant'
type MockTenantRepository_FetchTenant_Call struct {
	*mock.Call
}

// FetchTenant is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTenantRepository_Expecter) FetchTenant(ctx interface{}, id interface{}) *MockTenantRepository_FetchTenant_Call {
	return &MockTenantRepository_FetchTenant_Call{Call: _e.mock.On("FetchTenant", ctx, id)}
}

func (_c *MockTenantRepository_FetchTenant_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTenantRepository_FetchTenant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTenantRepository_FetchTenant_Call) Return(_a0 *profile.Tenant, _a1 error) *MockTenantRepository_FetchTenant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTenantRepository_FetchTenant_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*profile.Tenant, error)) *MockTenantRepository_FetchTenant_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTenantRepository creates a new instance of MockTenantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTenantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTenantRepository {
	mock := &MockTenantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
